---
- name: Copy rustup-init.sh
  become: true
  become_user: isucon
  copy:
    src: rustup-init.sh
    dest: /home/isucon/local/rustup-init.sh
    mode: 0755

- name: Install Rust
  become: true
  become_user: isucon
  shell:
    cmd: /usr/bin/sh -x /home/isucon/local/rustup-init.sh -y --no-modify-path --profile default --default-toolchain 1.82.0 -c rustfmt
    chdir: /home/isucon
